version: '3.8'

services:

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./full-stack/backend/.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./full-stack/backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
    env_file:
      - ./full-stack/backend/.env.dev
    volumes:
      - ./full-stack/backend:/app
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./full-stack/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - frontend:/app/dist
    env_file:
      - ./full-stack/frontend/.env.dev
    ports:
      - 5173:5173

volumes:
  db-data:
  frontend:
