FROM python:3.10-alpine

# Install dependencies and remove package lists to free up space
RUN apk update && apk add --no-cache postgresql-client

# Wait for the postgres db to start up
COPY ./full-stack/backend/wait-for-postgres.sh .
# make this file executable
RUN chmod +x /wait-for-postgres.sh

COPY ./full-stack/backend/requirements.txt .
RUN pip install -r requirements.txt

COPY ./full-stack/backend /app
WORKDIR /app

CMD ["/wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
